#!/bin/bash

# gcc -o xo src/xo_util.c src/xo_main.c -l bcm2835 -l pthread # for C
# g++ -o xo src/xo_util.cpp src/xo_main.cpp -l bcm2835 -l pthread # for C++

g++ -std=c++0x -c -o obj/xo_util.o src/xo_util.cpp 
g++ -std=c++0x -c -o obj/xo_main.o src/xo_main.cpp
g++ -std=c++0x -c -o obj/protocol_v1.o src/protocol_v1.cpp
g++ -std=c++0x -o xo obj/xo_util.o obj/xo_main.o obj/protocol_v1.o -l bcm2835 -l pthread
